# https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-20-04
# 
- name: Installs docker
  hosts: myhosts
  become: true
  roles:
    - role: docker
    - role: portainer
    - role: portainer-stack 
  tasks:
    - name: Shutdown the machine
      community.general.shutdown:
      tags: ['never', 'shutdown']