- name: Installs docker
  hosts: myhosts
  become: true
  vars:
    cloudflare_api_key: "{{lookup('dotenv', 'CLOUDFLARE_API_KEY')}}"
  roles:
    - role: docker
    - role: caddy
      tags: ['caddy']
  tasks:
    - name: Shutdown the machine
      community.general.shutdown:
      tags: ['never', 'shutdown']