- name: Installs docker
  hosts: myhosts
  become: true
  vars:
    apps_dir: "/docker"
    cloudflare_api_key: "{{lookup('dotenv', 'CLOUDFLARE_API_KEY')}}"
  roles:
    - role: docker
      tags: ['docker']
    - role: caddy
      tags: ['caddy']
    - role: portainer
  tasks:
    - name: Shutdown the machine
      community.general.shutdown:
      tags: ['never', 'shutdown']