- name: Installs docker
  hosts: myhosts
  become: true
  roles:
    - role: docker
    - role: caddy
      tags: ['caddy']
  tasks:
    - name: Shutdown the machine
      community.general.shutdown:
      tags: ['never', 'shutdown']