- name: Create apps directory
  ansible.builtin.file:
    path: /apps
    state: directory

- name: Create caddy directory
  ansible.builtin.file:
    path: /apps/caddy
    state: directory

- name: copy caddy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yaml
    dest: /apps/caddy/docker-compose.yaml