- name: Create apps directory
  ansible.builtin.file:
    path: "{{apps_dir}}"
    state: directory

- name: Create caddy directory
  ansible.builtin.file:
    path: "{{apps_dir}}/caddy"
    state: directory

- name: Create a network
  ansible.builtin.docker_network:
    name: proxy-network

- name: copy caddy docker-compose file
  ansible.builtin.template:
    src: "{{item}}"
    dest: "{{apps_dir}}/caddy/."
  with_fileglob: "{{role_path}}/templates/*"
  notify:
    - Restart caddy

- name: Start caddy with docker-compose
  community.docker.docker_compose_v2:
    project_src: "{{apps_dir}}/caddy"