networks:
  proxy-network:
    external: true

services:
  portainer:
    image: portainer/portainer-ee:lts
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - proxy-network
volumes:
  data: