services:
  portainer:
    image: portainer/portainer-ee:lts
    ports:
      - 9443:9443
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: ['--admin-password', '${PORTAINER_ADMIN_PASSWORD}', '--license-key', '${PORTAINER_LICENSE_KEY}']   
volumes:
  portainer-data: