networks:
  proxy-network:
    external: true

services:
  portainer:
    image: portainer/portainer-ee:lts
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: ['--admin-password', '${PORTAINER_ADMIN_PASSWORD}', '--license-key', '${PORTAINER_LICENSE_KEY}']   
    networks:
      - proxy-network
volumes:
  portainer-data: