

- name: Authenticate at portainer api
  ansible.builtin.uri:
    url: "{{portainer_host}}/api/auth"
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      username: "admin"
      password: "secretsecretsecret"
    validate_certs: false
  register: auth_response
  changed_when: false
  ignore_errors: true

- name: Print auth response
  ansible.builtin.debug:
    msg: "{{auth_response}}"