- name: Create apps directory
  ansible.builtin.file:
    path: "{{apps_dir}}"
    state: directory

- name: Create portainer directory
  ansible.builtin.file:
    path: "{{apps_dir}}/portainer"
    state: directory

- name: Copy portainer files
  ansible.builtin.template:
    src: "{{item}}"
    dest: "{{apps_dir}}/portainer/."
  with_fileglob: "{{role_path}}/templates/*"
  notify:
    - Restart portainer

- name: Install portainer
  community.docker.docker_compose_v2:
    project_src: "{{apps_dir}}/portainer"