- name: Copy portainer docker compose file
  ansible.builtin.copy:
    src: ./docker-compose
    dest: .

- name: Copy .env file
  ansible.builtin.copy:
    src: ./.env
    dest: "{{item}}"
  loop:
    - ./docker-compose/portainer/.env

- name: Install portainer
  community.docker.docker_compose_v2:
    project_src: ./docker-compose/portainer
    
- name: Remove .env files
  ansible.builtin.file:
    path: "{{item}}"
    state: absent
  loop:
    - ./docker-compose/portainer/.env