- name: Create authentik directory
  ansible.builtin.file:
    path: "{{apps_dir}}/authentik"
    state: directory
  
- name: Copy authentik files
  ansible.builtin.template:
    src: "{{item}}"
    dest: "{{apps_dir}}/authentik/."
  with_fileglob: 
    - "{{role_path}}/templates/*"
    - "{{role_path}}/templates/.*"
  notify:
    - Restart authentik

- name: Start authentik with docker-compose
  community.docker.docker_compose_v2:
    project_src: "{{apps_dir}}/authentik"